name: travel_impressions
version: 0.0.1

description: travel_impressions application that uses EDNetCore for its model.

homepage: https://ednet.dev


environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  ednet_core:
    path: ../../../ednet_cms/packages/ednet_core
  ednet_core_default_app:
    path: ../ednet_core_default_app
